---
## This task will re run some of the tasks that were intially skipped
## This file was added to main.yml to re run some of the skipped task after section 6 
## All errors can be ignore

- name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled"
  block:
      - name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            dest: /etc/modprobe.d/squashfs.conf
            regexp: '^(#)?install squashfs(\\s|$)'
            line: install squashfs /bin/true
            create: true

      - name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | Disable squashfs"
        community.general.modprobe:
            name: squashfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu22cis_rule_1_1_1_2
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.1.2
      - squashfs

- name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured"
  block:
      - name: "1.4.2 | AUDIT | Ensure permissions on bootloader config are configured | Check for Grub file"
        ansible.builtin.stat:
            path: "{{ ubtu22cis_grub_file }}"
        check_mode: false
        register: ubtu22cis_1_4_2_grub_cfg_status

      - name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured | Set permissions"
        ansible.builtin.file:
            path: "{{ ubtu22cis_grub_file }}"
            owner: root
            group: root
            mode: 0400
        when:
            - ubtu22cis_1_4_2_grub_cfg_status.stat.exists
  when:
      - ubtu22cis_rule_1_4_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.2
      - grub

- name: "3.5.2.2 | AUDIT | Ensure ufw is uninstalled or disabled with nftables"
  ansible.builtin.package:
      name: ufw
      state: absent
  when:
      - ubtu22cis_rule_3_5_2_2
      - ubtu22cis_firewall_package == "nftables"
  tags:
      - rule_3.5.2.2
      - nftables
  ignore_errors: yes

- name: "3.5.3.1.2 | PATCH | Ensure nftables is not installed with iptables"
  ansible.builtin.package:
      name: nftables
      state: absent
  when:
      - ubtu22cis_rule_3_5_3_1_2
      - ubtu22cis_firewall_package == "iptables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.3.1.2
      - iptables

- name: "4.2.1.1.1 | PATCH | Ensure systemd-journal-remote is installed"
  ansible.builtin.package:
      name: systemd-journal-remote
      state: present
  when:
      - ubtu22cis_rule_4_2_1_1_1
      - not ubtu22cis_system_is_log_server
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - journald
      - rule_4.2.1.1.1

- name: "4.2.1.1.2 | PATCH | Ensure systemd-journal-remote is configured"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journal-upload.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  notify: Restart journald
  loop:
      - { regexp: 'URL=', line: 'URL={{ ubtu22cis_remote_log_server }}'}
      - { regexp: 'ServerKeyFile=', line: 'ServerKeyFile={{ ubtu22cis_journal_upload_serverkeyfile }}'}
      - { regexp: 'ServerCertificateFile=', line: 'ServerCertificateFile={{ ubtu22cis_journal_servercertificatefile }}'}
      - { regexp: 'TrustedCertificateFile=', line: 'TrustedCertificateFile={{ ubtu22cis_journal_trustedcertificatefile }}'}
  when:
      - ubtu22cis_rule_4_2_1_1_2
      - not ubtu22cis_system_is_log_server
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - journald
      - rule_4.2.1.1.2

- name: "4.2.1.1.3 | PATCH | Ensure systemd-journal-remote is enabled"
  ansible.builtin.systemd:
      name: systemd-journal-upload
      state: started
      enabled: true
  when:
      - not ubtu22cis_system_is_log_server
      - ubtu22cis_rule_4_2_1_1_3
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - journald
      - rule_4.2.1.1.3

- name: "4.2.1.1.4 | PATCH | Ensure journald is not configured to recieve logs from a remote client"
  ansible.builtin.systemd:
      name: systemd-journal-remote.socket
      state: stopped
      enabled: false
      masked: true
  when:
      - not ubtu22cis_system_is_log_server
      - ubtu22cis_rule_4_2_1_1_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - journald
      - rule_4.2.1.1.4

- name: "4.2.1.2 | PATCH | Ensure journald service is enabled"
  block:
      - name: "4.2.1.2 | AUDIT | Ensure journald service is enabled | Capture status"
        ansible.builtin.shell: systemctl is-enabled systemd-journald.service
        changed_when: false
        failed_when: false
        register: ubtu22cis_4_2_1_2_status

      - name: "4.2.2.2 | AUDIT | Ensure journald service is enabled | Alert on bad status"
        ansible.builtin.debug:
            msg:
                - "Warning!! The status of systemd-journald should be static and it is not. Please investigate"
        when: "'static' not in ubtu22cis_4_2_1_2_status.stdout"

      - name: "4.2.2.2 | AUDIT | Ensure journald service is enabled | Warn Count"
        ansible.builtin.import_tasks: warning_facts.yml
        when: "'static' not in ubtu22cis_4_2_1_2_status.stdout"
  vars:
      warn_control_id: '4.2.1.2'
  when:
      - ubtu22cis_rule_4_2_1_2
  tags:
      - level1-server
      - level1-workstation
      - audit
      - journald
      - rule_4.2.1.2

- name: "4.2.1.3 | PATCH | Ensure journald is configured to compress large log files"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^(#|)Compress='
      line: Compress=yes
  notify: Restart journald
  when:
      - ubtu22cis_rule_4_2_1_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - journald
      - rule_4.2.1.3

- name: "4.2.1.4 | PATCH | Ensure journald is configured to write logfiles to persistent disk"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^(#|)Storage='
      line: Storage=persistent
  notify: Restart journald
  when:
      - ubtu22cis_rule_4_2_1_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - journald
      - rule_4.2.1.4

- name: "4.2.1.5 | PATCH | Ensure journald is not configured to send logs to rsyslog"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^ForwardToSyslog='
      line: '#ForwardToSyslog=yes'
  notify: Restart journald
  when:
      - ubtu22cis_rule_4_2_1_5
  tags:
      - level1-server
      - level2-workstation
      - manual
      - patch
      - journald
      - rule_4.2.1.5

- name: "4.2.1.6 | PATCH | Ensure journald log rotation is configured per site policy"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  notify: Restart journald
  loop:
      - { regexp: '^#SystemMaxUse=|^SystemMaxUse=', line: '{{ ubtu22cis_journald_systemmaxuse | default ("#SystemMaxUse") }}'}
      - { regexp: '^#SystemKeepFree=|^SystemKeepFree=', line: '{{ ubtu22cis_journald_systemkeepfree | default ("#SystemKeepFree")}}' }
      - { regexp: '^#RuntimeMaxUse=|^RuntimeMaxUse=', line: '{{ ubtu22cis_journald_runtimemaxuse | default ("#RuntimeMaxUse") }}'}
      - { regexp: '^#RuntimeKeepFree=|^RuntimeKeepFree=', line: '{{ ubtu22cis_journald_runtimekeepfree | default ("#RuntimeKeepFree") }}'}
      - { regexp: '^#MaxFileSec=|^MaxFileSec=', line: '{{ ubtu22cis_journald_maxfilesec | default ("#MaxFileSec") }}'}
  when:
      - ubtu22cis_rule_4_2_1_6
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - journald
      - rule_4.2.1.6
  
